[package]
name = "mdbook-dice"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4.36" # Use the latest version compatible with your mdBook version
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1"
clap = "3.0"
semver = "1.0"
