name: Release mdbook-dice

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-upload:
    name: Build and Upload Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Upload Rust Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: mdbook-dice
          token: ${{ secrets.GITHUB_TOKEN }}
